defmodule Fate.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:participants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:color, :text, null: false, default: "#3b82f6")
    end

    create table(:events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :parent_id,
        references(:events,
          column: :id,
          name: "events_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:type, :text, null: false)
      add(:actor_id, :text)
      add(:target_id, :text)
      add(:exchange_id, :uuid)
      add(:description, :text)
      add(:detail, :map)
    end

    create table(:branches, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:status, :text, null: false, default: "active")

      add(
        :head_event_id,
        references(:events,
          column: :id,
          name: "branches_head_event_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:branch_participants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text, null: false)
      add(:seat_index, :bigint, null: false)

      add(
        :branch_id,
        references(:branches,
          column: :id,
          name: "branch_participants_branch_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :participant_id,
        references(:participants,
          column: :id,
          name: "branch_participants_participant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:branch_participants, "branch_participants_branch_id_fkey"))

    drop(constraint(:branch_participants, "branch_participants_participant_id_fkey"))

    drop(table(:branch_participants))

    drop(constraint(:branches, "branches_head_event_id_fkey"))

    drop(table(:branches))

    drop(constraint(:events, "events_parent_id_fkey"))

    drop(table(:events))

    drop(table(:participants))
  end
end
