defmodule Fate.Repo.Migrations.InitialSetup do
  @moduledoc """
  Creates the core schema with final table names.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:participants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:color, :text, null: false, default: "#3b82f6")
    end

    create table(:events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :parent_id,
        references(:events,
          column: :id,
          name: "events_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:type, :text, null: false)
      add(:actor_id, :text)
      add(:target_id, :text)
      add(:exchange_id, :uuid)
      add(:description, :text)
      add(:detail, :map)
    end

    create table(:bookmarks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:status, :text, null: false, default: "active")

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :head_event_id,
        references(:events,
          column: :id,
          name: "bookmarks_head_event_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :parent_bookmark_id,
        references(:bookmarks,
          column: :id,
          name: "bookmarks_parent_bookmark_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:bookmark_participants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text, null: false)
      add(:seat_index, :bigint, null: false)

      add(
        :bookmark_id,
        references(:bookmarks,
          column: :id,
          name: "bookmark_participants_bookmark_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :participant_id,
        references(:participants,
          column: :id,
          name: "bookmark_participants_participant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:bookmark_participants, "bookmark_participants_bookmark_id_fkey"))
    drop(constraint(:bookmark_participants, "bookmark_participants_participant_id_fkey"))
    drop(table(:bookmark_participants))

    drop(constraint(:bookmarks, "bookmarks_head_event_id_fkey"))
    drop(constraint(:bookmarks, "bookmarks_parent_bookmark_id_fkey"))
    drop(table(:bookmarks))

    drop(constraint(:events, "events_parent_id_fkey"))
    drop(table(:events))

    drop(table(:participants))
  end
end
